### ISSUE TITLE
Add support to sound alerts

### ISSUE THREAD

**Issue by dougmaitelli** [Brunas/HomeAssistant#1]
Hey,

Thanks for the blueprint. I am just opening this as a suggestion to have another parameter for the sound property allowing the alerts to ring a sound.

Thanks,

**Comment by Brunas** [comment]
Hi,

It makes sense. Will try to think of something when I have time for that :).

**Comment by dougmaitelli** [comment]
It would be something like this: https://github.com/Brunas/HomeAssistant/pull/2

I am not currently able to test this due to a bug with my calendar integration tho.

**Comment by Brunas** [comment]
Hi,

I've implemented sound map for different sounds for different events.

**Comment by dougmaitelli** [comment]
Hi @Brunas, thanks!

On a side note, I noticed the blueprint throws errors when it fails to get the icon from the icon map.  Would be a good idea to have a fallback icon and fallback sound when the map is either empty or does not contain the event key.

**Comment by Brunas** [comment]
Hey @dougmaitelli, happy 2024!

Thanks for being great tester ;). I've pushed minor change to just check if those values are defined in json. At least for me no more complains in HA log. AFAIK Awtrix is not complaining about icon and sound values being empty strings anyway.

**Comment by dougmaitelli** [comment]
Thanks! Happy new year @Brunas! 

To me now there is only one last thing that I feel like is missing. The ability to have a "default" sound an icon when they are not in the map. Maybe if there is nothing on the map for the event name it could look for the value "default" if it exists and if not just keep the value empty?

I have many different events and don't really want to create a value in the map for each one since I just want to use the same icon and sound for all.

What do you think?

**Comment by Brunas** [comment]
Hi @dougmaitelli,

I've amended blueprint and added empty default values default_icon and default_sound. Hope that is ok for you :)

**Comment by dougmaitelli** [comment]
Hey,

Sorry for the late reply, finally had time to test it, notifications are working but the sound is not for some reason.
I have a melody called "alert", if I call awtrix MQTT directly with that sound it works, but thru the automation the notifications never have sound.

Btw, my sound map is just an empty json `{}` and default sound is `alert`

**Comment by Brunas** [comment]
Hi @dougmaitelli,

Sorry for another long reply, but no time for any hobbies :)
After deeper looking into awtrix code I found why sound is not played. Unfortunately since I'm sending calendar notifications as custom app sounds are not supported :(. However, they are supported in one time notification or simple sound message which I think is the way to go. The plan is to send both custom app with all details and sound messages at least once. The main question is how often I need to send that sound. I would say for sure at the time of event and at hours_before moment.

**Comment by Brunas** [comment]
@dougmaitelli,

I've added separate sound topic and sounds are sent from event start time till end time every 5 minutes which sometimes make everyone around really angry, be careful. Personally, I've removed sounds from settings ;)
